project:
  type: website

website:
  title: "RPsyche"
  navbar:
    left:
      - href: folien/uebersicht.qmd
        text: Folien
      - href: themenuebersicht.qmd
        text: Themenübersicht
      - href: ueber-uns.qmd
        text: Wer sind wir?

format:
  html:
    theme: journal
    css: styles.css
    toc: true


