---
title: "Grundlagen der Programmierung für Psychologie-Erstis"
---

:::: { .card .flex }
::: {}
[**Dienstags**]{ .x-large }

[12-14 Uhr]{ .xx-large }
:::

::: { style="text-align: right" }
[**Raum**]{ .x-large }

[3322]{ .xx-large }
:::

::::

In der modernen Wissenschaft sind Programmierkenntnisse äußerst hilfreich. Sie ermöglichen die Analyse großer Datenmengen und die Automatisierung aufwändiger Forschungsprozesse durch Computerprogramme. Ihr werdet schnell feststellen, dass Psychologie hier keine Ausnahme bildet. In euren ersten zwei Semestern werdet ihr in Statistik 1 und Statistik 2 die Grundlagen der Statistik lernen und *bisschen* in [R](https://en.wikipedia.org/wiki/R_(programming_language)) programmieren. Im zweiten Semester werdet ihr erstmals an einem kleinen Forschungsprojekt (Empra) teilnehmen. Spätestens hier werdet ihr deutlich sehen, wie nützlich Programmierkenntnisse sein können.

Man studiert nicht unbedingt Psychologie, um mit Zahlen und Codes um sich zu schmeissen - das ist uns klar. Zumindest ist das Programmieren nicht der übliche Grund für die Wahl dieses Studiums. Man profitiert allerdings erheblich davon, wenn man es kann. Und noch viel wichtiger: Programmieren macht Spaß!

## Das Konzept
Unser Kurs wird abwechselnd reguläre Sitzungen und Exkursionssitzungen anbieten. In regulären Sitzungen werden wir uns mit den Grundlagen von R beschäftigen. Das hilft euch dann auch schon direkt für die ersten beiden Statistikmodule. In Exkurssitzungen behandeln wir andere Konzepte und Tools, die für Psychologen hilfreich sein könnten. Wenn du dich ausschließlich für R interessierst, kannst du auch nur die R-Sitzungen im zweiwöchigen Rhythmus besuchen. Eine vorläufige Übersicht der Themen findest du [hier](topics.qmd). Außerdem freuen wir uns in den Sitzungen Ideen von euch zu integrieren und zu spannenden Diskussionen anzuregen.

## Für wen ist dieser Kurs gedacht?
Jeder, der das Programmieren lernen möchte, ist herzlich eingeladen, teilzunehmen. Wir werden versuchen, so gut es geht, euch bei auftretenden Problemen zu unterstützen. Allerdings sind wir selbst längst keine Profis und wollen gern mit euch zusammen lernen! Diejenigen, die motiviert sind, die vorgestellten Ideen und Konzepte auch über den Kurs hinaus weiterzuverfolgen, werden wahrscheinlich den größten Nutzen aus diesem Kurs ziehen.


## Warum wollten wir diesen Kurs organisieren?
Obwohl wir im Rahmen des Psychologiestudiums immer wieder mit R in Berührung kommen, erhalten wir nie eine umfassende Einführung. Das führt oft zur Frustration und wirkt demotivierend. Der unnötige Stress, der durch die anfangs vielleicht überfordernden Programme entsteht, steht jedoch in keinem Verhältnis zu der eigentlichen Schwierigkeit des Programmierens. Das hat zur Folge, dass viele Studenten die Arbeit mit R vernachlässigen und die Statistikkonzepte für die Klasuren auswendig lernen, ohne sie genau zu verstehen, geschweige denn, sie sinnvoll anwenden zu können. 

Die Idee zur Organisation dieses Kurses entstand, als wir uns in einer Empra-Sitzung darüber beschwerten, dass wir auf einmal viel mit R arbeiten mussten, ohne überhaupt die notwendigen Grundkenntnisse zu besitzen. Wir haben uns gefragt, warum man an der Uni nicht zumindest die Basics der Programmierung lernt. Grundlegende Programmierkenntnisse helfen euch nämlich nicht nur während des Studiums leichter und effizienter Statistik zu lernen, sondern öffnen darüber hinaus auch noch eine Menge an Anwendungsfeldern und Berufsmöglichkeiten für Psycholog:innen. So gibt es beispielsweise weitere grundlegende technische Konzepte, wie [version control](https://en.wikipedia.org/wiki/Version_control), denen man an der Uni leider erst viel später begegnet, obwohl sie von Beginn an wahnsinnig nützlich sind. Unser Ziel ist es, euch eine bessere und freundlichere Einführung in diese Themen zu bieten. Dieser Kurs wird von Studierenden für Studierende organisiert und ist experimentell!

---

Für fragen: [alp@rpsyche.de](mailto:alp@rpsyche.de)
