---
title: "Wer sind wir?"
---

## Alp Kaan Aksu
Ich studiere Psychologie in meinem 3. Semester an der LMU und Informatik in meinem 5. Semester an der TUM.

{{< fa globe >}} [alpkaanaksu.com](https://alpkaanaksu.com)

{{< fa brands github >}} [alpkaanaksu](https://github.com/alpkaanaksu)


## Martin Wiehr
Ich studiere ebenfalls Psychologie im 3. Semester an der LMU. Nebenher mache ich zwar kein zusätzliches Informatik Studium bin aber trotzdem am Programmieren interessiert.

{{< fa brands github >}} [MWiehr](https://github.com/MWiehr)


## Caspar Schumacher
Auch ich bin Psychologiestudent im 3. Semester. Programmieren fand ich schon immer spannend, jedoch habe ich mich bisher nicht so recht alleine daran gewagt. Mit R habe ich dann meine ersten Schritte gemacht und erkannt, wie nützlich ein gewisses Maß an Informatikkenntnissen auch für Psychologen sein kann. So entstand die Idee, in diesem Kurs von Grund auf zusammen mit Gleichgesinnten zu lernen!

{{< fa brands github >}} [CasparSchumacher](https://github.com/CasparSchumacher)

## Benedikt Ehrenwirth
Auch ich studiere zusammen mit den anderen Psychologie im 3. Semester. Ich interessiere mich privat für informatische Themen und glaube, dass einem bereits ein grundlegendes Verständnis der Prinzipien des Programmierens genug mit an die Hand gibt, um die eigenen Programmierprojekte selbstständig auszubauen.

{{< fa brands github >}} [Benedikt Ehrenwirth](https://github.com/Cornflames)

---

Vielen Dank an [Prof. Dr. Felix Schönbrodt](https://www.psy.lmu.de/pm/personen/lehrstuhlmitarbeiter/schoenbrodt/index.html) für seine Hilfe und Unterstützung.
