---
title: "Rmarkdown & Good coding practices"
author:
  - name:
    email:
date: 2023-12-12
date-format: "DD.MM.YY"
footer: "RMarkdown & Good coding practices"
execute: 
  echo: true
  error: true
format: 
  clean-revealjs: 
    output-ext: slide.html
    transition: slide
    background-transition: fade
    touch: true
    embed-resources: true
    css: reveal_styles.css
  html: default
---

## Was ist RMarkdown?

Kurz gesagt ist RMarkdown grundsätzlich eine Erweiterung der Markdown-Syntax, die es uns ermöglicht, R-Code und dessen Output in unseren Markdown-Text einzubetten (und weitere Formattierungen vorzunehmen). Darüber hinaus ist RMarkdown ein Paket, das es möglicht macht, diesen Markdown-Text zu komplizierten, professionellen Dokumenten in verschiedenen Formaten zu rendern.

Auch wenn es komplizierter klingt, ist es oft sehr viel einfacher, zeitsparender und automatisierter, als Formatierungen in WYSIWYG-Programmen wie Word händisch vorzunehmen. Darüber hinaus bietet es noch weitere Vorteile.

### Welche Vorteile bietet Markdown?

Markown ermöglicht es, die Formattierung von Text ebenfalls als Text in diesen zu integrieren. Ein Computer kümmert sich dann darum, den Markup-Text zu einem schönen Dokument zu rendern. Das birgt den großen Vorteil, dass wir beim Texteschreiben nicht an ein Textprogramm gebunden sind, das Formatierungen typischerweise in seinem eigenen Format speichert. Derselbe "abstrakte" Markup-Text kann hingegen von unterschiedlichen Programmen auf unterschiedliche Weise gerendert werden. Wir können also für verschiedene Dokumentformate verschiedene Programme nutzen, die die einfachen Markdown-Formatierungen zu beliebig komplizierten dokumentspezifischen Formatierungen (z.B. APA-Style!) rendert.

### Welche Vorteile bietet das Einbetten von R-Code?

Als Psychologen berichten wir häufig Daten und Berechnungen. Statt dem händischen Copy-und-Pasten aus Datensätzen oder den Ergebnissen unseres Taschenrechners, können wir den Code zur Berechnung und Datenextraktion direkt in unsere .Rmd-Datei schreiben und ihren Output einbetten.

Das hat entscheidende Vorteile: - Wir und andere sehen, wo und wie wir etwas gemacht haben, Code und Text sind in einem Dokument vereint. - Bei Änderungen der Daten oder Berechnungsverfahren müssen wir die Ergebnisse nicht händisch neu einfügen, sondern können den Code einfach neu ausführen! (Solange der Code nach wie vor anwendbar ist) - Wir vermeiden Fehler beim Copy-und-Pasten!!!

## Wie sieht eine .Rmd-Datei genau aus?

### Was sind Codezellen?

Codezellen sind abgeschlossene Blöcke zwischen unserem regulären Markdown-Text, der R-Code enthält. Man unterscheidet: 1. R code-chunks: Mehrzeilige Codeblöcke 2. Inline R-code: einzeiliger, mitten im Text eingebetter Block mit einem R-Befehl.

Das Output-Verhalten von Code-Chunks kann durch sogenannte chunk-options am Anfang eines Blocks gesteuert werden.

### Was ist der YAML-Header?

Der YAML-Header ist ein Abschnitt am Anfang unserer .Rmd-Datei, der nicht im finalen Dokument enthalten sein wird. Dennoch hat er einen Einfluss auf das finale Dokument und ist sehr wichtig.

Das liegt daran, dass er Metadaten über unser Dokument enthält, anhand deren Festlegung wir den Renderprozess und das finale Dokument steuern können. Man könnte also sagen, dass er die "Einstellungen" unseres Dokumentes darstellt.
